### ISSUE TITLE
Cannot compile on 5.11

### ISSUE THREAD

**Issue by hrchu** [markh794/mhvtl#62]
Wondering what kernel version is compatible currently?

```
root@dev:~/mhvtl/kernel# make
make -C /lib/modules/5.11.0-22-generic/build M=/root/mhvtl/kernel modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-22-generic'
  CC [M]  /root/mhvtl/kernel/mhvtl.o
/root/mhvtl/kernel/mhvtl.c:347:3: error: ‘const struct file_operations’ has no member named ‘ioctl’
  347 |  .ioctl  = vtl_c_ioctl_bkl,
      |   ^~~~~
/root/mhvtl/kernel/mhvtl.c:347:12: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  347 |  .ioctl  = vtl_c_ioctl_bkl,
      |            ^~~~~~~~~~~~~~~
/root/mhvtl/kernel/mhvtl.c:347:12: note: (near initialization for ‘vtl_fops’)
/root/mhvtl/kernel/mhvtl.c:347:12: error: initialization of ‘loff_t (*)(struct file *, loff_t,  int)’ {aka ‘long long int (*)(struct file *, long long int,  int)’} from incompatible pointer type ‘int (*)(struct inode *, struct file *, unsigned int,  long unsigned int)’ [-Werror=incompatible-pointer-types]
/root/mhvtl/kernel/mhvtl.c:347:12: note: (near initialization for ‘vtl_fops.llseek’)
/root/mhvtl/kernel/mhvtl.c:1695:13: warning: ‘vtl_c_ioctl’ defined but not used [-Wunused-function]
 1695 | static long vtl_c_ioctl(struct file *file, unsigned int cmd, unsigned long arg)
      |             ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:287: /root/mhvtl/kernel/mhvtl.o] Error 1
make[1]: *** [Makefile:1848: /root/mhvtl/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-22-generic'

```

**Comment by markh794** [comment]
Just added a patch for this.
The 'HAVE_UNLOCKED_IOCTL' define was removed in 5.9+ resulting in older code being pulled in.

**Comment by markh794** [comment]
`commit fa114bf6563a466c8b5ecf4b10f8c62a7074146b
Author: Mark Harvey <markh794@gmail.com>
Date:   Tue Jul 20 15:42:28 2021 +1000

    mhvtl.ko: reinstate HAVE_UNLOCKED_IOCTL
    
    As of kernel 5.9+ HAVE_UNLOCKED_IOCTL has been removed from linux/fs.h
    
    Signed-off-by: Mark Harvey <markh794@gmail.com>`

**Comment by markh794** [comment]
.
