### ISSUE TITLE
mhvtl kernel driver does not work with new 5.14 linux kernel

### ISSUE THREAD

**Issue by gonzoleeman** [markh794/mhvtl#65]
The kernel driver uses DRIVER_SENSE, but that define has been removed. Actually, the whole sense data usage has changed, so there is not a trivial (simple substitution) solution.

Output looks like:

```
+ make -C /usr/src/linux-obj/x86_64/default 'EXTRA_CFLAGS=-Iinclude -DMHVTL_DEBUG -DHAVE_UNLOCKED_IOCTL' modules M=/home/abuild/rpmbuild/BUILD/mhvtl-1.63_release+754.ff8861da60c9/obj/default
 make: Entering directory '/usr/src/linux-5.14.0-1-obj/x86_64/default'
  CC [M]  /home/abuild/rpmbuild/BUILD/mhvtl-1.63_release+754.ff8861da60c9/obj/default/mhvtl.o
 /home/abuild/rpmbuild/BUILD/mhvtl-1.63_release+754.ff8861da60c9/obj/default/mhvtl.c:248:18: error: 'DRIVER_SENSE' undeclared here (not in a function)
   248 |                 (DRIVER_SENSE << 24) | SAM_STAT_CHECK_CONDITION;
       |                  ^~~~~~~~~~~~
 make[2]: *** [/usr/src/linux-5.14.0-1/scripts/Makefile.build:272: /home/abuild/rpmbuild/BUILD/mhvtl-1.63_release+754.ff8861da60c9/obj/default/mhvtl.o] Error 1
 make[1]: *** [/usr/src/linux-5.14.0-1/Makefile:1865: /home/abuild/rpmbuild/BUILD/mhvtl-1.63_release+754.ff8861da60c9/obj/default] Error 2
 make: *** [../../../linux-5.14.0-1/Makefile:220: __sub-make] Error 2
```

**Comment by markh794** [comment]
Thanks for the heads up

**Comment by markh794** [comment]
Just pushed fix via : 35ddb48e5262dfe1d9fba987323b425bad0598ac,
Thanks once again for the bug report.
