### ISSUE TITLE
Compile on el9 /  5.14 kernel

### ISSUE THREAD

**Issue by mesekem** [markh794/mhvtl#111]
Had issues compiling the kernel module with RHEL 9.0.

  CC [M]  /tmp/mhvtl-master/kernel/mhvtl.o
/tmp/mhvtl-master/kernel/mhvtl.c:248:18: error: ‘DRIVER_SENSE’ undeclared here (not in a function)
  248 |                 (DRIVER_SENSE << 24) | SAM_STAT_CHECK_CONDITION;
      |                  ^~~~~~~~~~~~
/tmp/mhvtl-master/kernel/mhvtl.c:331:10: error: ‘struct scsi_host_template’ has no member named ‘unchecked_isa_dma’
  331 |         .unchecked_isa_dma =    0,
      |          ^~~~~~~~~~~~~~~~~
/tmp/mhvtl-master/kernel/mhvtl.c:345:10: error: ‘const struct file_operations’ has no member named ‘ioctl’
  345 |         .ioctl          = vtl_c_ioctl_bkl,
      |          ^~~~~
/tmp/mhvtl-master/kernel/mhvtl.c:345:27: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  345 |         .ioctl          = vtl_c_ioctl_bkl,
      |                           ^~~~~~~~~~~~~~~
/tmp/mhvtl-master/kernel/mhvtl.c:345:27: note: (near initialization for ‘vtl_fops’)
/tmp/mhvtl-master/kernel/mhvtl.c:345:27: error: initialization of ‘loff_t (*)(struct file *, loff_t,  int)’ {aka ‘long long int (*)(struct file *, long long int,  int)’} from incompatible pointer type ‘int (*)(struct inode *, struct file *, unsigned int,  long unsigned int)’ [-Werror=incompatible-pointer-types]
/tmp/mhvtl-master/kernel/mhvtl.c:345:27: note: (near initialization for ‘vtl_fops.llseek’)
In file included from /tmp/mhvtl-master/kernel/mhvtl.c:353:
/tmp/mhvtl-master/kernel/fetch50.c: In function ‘vtl_sg_copy_user’:
/tmp/mhvtl-master/kernel/fetch50.c:57:25: error: implicit declaration of function ‘flush_kernel_dcache_page’; did you mean ‘flush_kernel_vmap_range’? [-Werror=implicit-function-declaration]
   57 |                         flush_kernel_dcache_page(miter.page);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
      |                         flush_kernel_vmap_range
